apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx-1
  namespace: ngnx
spec:
  replicas: 6
  selector:
    matchLabels:
      name: test-nginx-1
  template:
    metadata:
      labels:
        name: test-nginx-1
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: test-nginx-1
---
apiVersion: v1
kind: Service
metadata:
  name: test-nginx-lb-1
  namespace: ngnx
spec:
  selector:
    name: test-nginx-1
  ports:
  - name: tcp
    port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
