apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx
  namespace: ngnx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: test-nginx
  template:
    metadata:
      labels:
        name: test-nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: test-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: test-nginx-lb
  namespace: ngnx
spec:
  selector:
    name: test-nginx
  ports:
  - name: tcp
    port: 8080
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
